version: 2.1

jobs:
  checkout:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout

  build:
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      - run:
          name: Build Docker Image
          command: |
            docker build -t your-image-name .

  push:
    docker:
      - image: circleci/docker:latest
    steps:
      - run:
          name: Log in to Docker Hub
          command: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - run:
          name: Push Docker Image
          command: docker push your-image-name

  deploy:
    machine:
      enabled: true
    steps:
      - run:
          name: Pull Docker Image
          command: docker pull your-image-name
      - run:
          name: Run Docker Container
          command: docker run -d -p 80:80 your-image-name

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - checkout
      - build:
          requires:
            - checkout
      - push:
          requires:
            - build
      - deploy:
          requires:
            - push
